<?php
session_start();
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/header.php';

redirectIfNotLoggedIn();
if (!isStaff()) {
    header('Location: /community-health-tracker/');
    exit();
}

// Check if PDF data exists in session
if (!isset($_SESSION['pdf_export_data']) || empty($_SESSION['pdf_export_data'])) {
    die('No data to generate PDF');
}

$patients = $_SESSION['pdf_export_data'];

// Include TCPDF library
require_once __DIR__ . '/../vendor/tcpdf/tcpdf.php';

// Create new PDF document
$pdf = new TCPDF('L', 'mm', 'A4', true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('Barangay Luz Health Center');
$pdf->SetAuthor('Barangay Luz Health Center');
$pdf->SetTitle('Patient Health Records Export');
$pdf->SetSubject('Patient Health Records');
$pdf->SetKeywords('Patient, Health, Records, Export, Medical');

// Remove default header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// Set margins
$pdf->SetMargins(15, 15, 15);
$pdf->SetAutoPageBreak(TRUE, 15);

// Add a page
$pdf->AddPage();

// Define colors
$headerColor = array(52, 152, 219); // Blue
$secondaryColor = array(44, 62, 80); // Dark blue
$lightGray = array(248, 249, 250); // Light gray
$borderColor = array(226, 232, 240); // Border gray

// Add header with logo and title
$pdf->SetFont('helvetica', 'B', 24);
$pdf->SetTextColor($headerColor[0], $headerColor[1], $headerColor[2]);
$pdf->Cell(0, 15, 'BARANGAY LUZ HEALTH CENTER', 0, 1, 'C');
$pdf->SetFont('helvetica', '', 14);
$pdf->SetTextColor($secondaryColor[0], $secondaryColor[1], $secondaryColor[2]);
$pdf->Cell(0, 8, 'PATIENT HEALTH RECORDS', 0, 1, 'C');
$pdf->SetFont('helvetica', '', 10);
$pdf->SetTextColor(100, 100, 100);
$pdf->Cell(0, 6, 'Generated on: ' . date('F j, Y h:i A'), 0, 1, 'C');
$pdf->Cell(0, 6, 'Generated by: ' . $_SESSION['user']['full_name'], 0, 1, 'C');
$pdf->Cell(0, 6, 'Total Records: ' . count($patients), 0, 1, 'C');
$pdf->Ln(10);

// Start creating patient records
foreach ($patients as $index => $patient) {
    // Add page break if not first patient and space is limited
    if ($index > 0) {
        $pdf->AddPage();
    }
    
    // Patient header
    $pdf->SetFont('helvetica', 'B', 16);
    $pdf->SetTextColor($secondaryColor[0], $secondaryColor[1], $secondaryColor[2]);
    $pdf->Cell(0, 10, 'PATIENT #' . ($index + 1) . ': ' . strtoupper($patient['full_name']), 0, 1);
    $pdf->SetDrawColor($headerColor[0], $headerColor[1], $headerColor[2]);
    $pdf->Line(15, $pdf->GetY(), 290, $pdf->GetY());
    $pdf->Ln(5);
    
    // ============ PERSONAL INFORMATION SECTION ============
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->SetFillColor($lightGray[0], $lightGray[1], $lightGray[2]);
    $pdf->SetTextColor($headerColor[0], $headerColor[1], $headerColor[2]);
    $pdf->Cell(0, 8, 'PERSONAL INFORMATION', 1, 1, 'L', true);
    $pdf->SetFont('helvetica', '', 10);
    $pdf->SetTextColor(0, 0, 0);
    
    // Personal Info Table
    $personalData = array(
        array('Patient ID:', $patient['id'] ?? 'N/A'),
        array('Full Name:', htmlspecialchars($patient['full_name'] ?? 'N/A')),
        array('Date of Birth:', !empty($patient['date_of_birth']) ? date('F j, Y', strtotime($patient['date_of_birth'])) : 'N/A'),
        array('Age:', $patient['age'] ?? 'N/A'),
        array('Gender:', htmlspecialchars($patient['gender'] ?? 'N/A')),
        array('Civil Status:', htmlspecialchars($patient['civil_status'] ?? 'N/A')),
        array('Occupation:', htmlspecialchars($patient['occupation'] ?? 'N/A')),
        array('Address:', htmlspecialchars($patient['address'] ?? 'N/A')),
        array('Sitio:', htmlspecialchars($patient['sitio'] ?? 'N/A')),
        array('Contact:', htmlspecialchars($patient['contact'] ?? 'N/A')),
        array('Patient Type:', $patient['patient_type'] ?? 'Regular Patient'),
    );
    
    foreach ($personalData as $row) {
        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->Cell(50, 7, $row[0], 0, 0, 'L');
        $pdf->SetFont('helvetica', '', 10);
        $pdf->Cell(0, 7, $row[1], 0, 1, 'L');
    }
    $pdf->Ln(5);
    
    // ============ MEDICAL INFORMATION SECTION ============
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->SetFillColor($lightGray[0], $lightGray[1], $lightGray[2]);
    $pdf->SetTextColor($headerColor[0], $headerColor[1], $headerColor[2]);
    $pdf->Cell(0, 8, 'MEDICAL INFORMATION', 1, 1, 'L', true);
    $pdf->SetFont('helvetica', '', 10);
    $pdf->SetTextColor(0, 0, 0);
    
    // Medical Info Table
    $medicalData = array(
        array('Height (cm):', $patient['height'] ?? 'N/A'),
        array('Weight (kg):', $patient['weight'] ?? 'N/A'),
        array('BMI:', calculateBMI($patient['height'] ?? 0, $patient['weight'] ?? 0)),
        array('Temperature (°C):', $patient['temperature'] ?? 'N/A'),
        array('Blood Pressure:', htmlspecialchars($patient['blood_pressure'] ?? 'N/A')),
        array('Blood Type:', htmlspecialchars($patient['blood_type'] ?? 'N/A')),
        array('PHIC No:', htmlspecialchars($patient['phic_no'] ?? 'N/A')),
        array('BHW Assigned:', htmlspecialchars($patient['bhw_assigned'] ?? 'N/A')),
        array('Family No:', htmlspecialchars($patient['family_no'] ?? 'N/A')),
        array('4P\'s Member:', htmlspecialchars($patient['fourps_member'] ?? 'No')),
        array('Last Checkup:', !empty($patient['last_checkup']) ? date('F j, Y', strtotime($patient['last_checkup'])) : 'N/A'),
    );
    
    foreach ($medicalData as $row) {
        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->Cell(50, 7, $row[0], 0, 0, 'L');
        $pdf->SetFont('helvetica', '', 10);
        $pdf->Cell(0, 7, $row[1], 0, 1, 'L');
    }
    $pdf->Ln(5);
    
    // ============ MEDICAL HISTORY SECTION ============
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->SetFillColor($lightGray[0], $lightGray[1], $lightGray[2]);
    $pdf->SetTextColor($headerColor[0], $headerColor[1], $headerColor[2]);
    $pdf->Cell(0, 8, 'MEDICAL HISTORY', 1, 1, 'L', true);
    $pdf->SetFont('helvetica', '', 10);
    $pdf->SetTextColor(0, 0, 0);
    
    $historyData = array(
        array('Allergies:', htmlspecialchars($patient['allergies'] ?? 'None recorded')),
        array('Chronic Conditions:', htmlspecialchars($patient['chronic_conditions'] ?? 'None recorded')),
        array('Immunization Record:', htmlspecialchars($patient['immunization_record'] ?? 'None recorded')),
        array('Current Medications:', htmlspecialchars($patient['current_medications'] ?? 'None')),
        array('Medical History:', htmlspecialchars($patient['medical_history'] ?? 'None recorded')),
        array('Family History:', htmlspecialchars($patient['family_history'] ?? 'None recorded')),
    );
    
    foreach ($historyData as $row) {
        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->Cell(50, 7, $row[0], 0, 0, 'L');
        $pdf->SetFont('helvetica', '', 10);
        
        // Handle long text with multi-line cells
        $text = $row[1];
        if (strlen($text) > 60) {
            $pdf->MultiCell(0, 7, $text, 0, 'L');
        } else {
            $pdf->Cell(0, 7, $text, 0, 1, 'L');
        }
    }
    
    // ============ REGISTRATION INFO SECTION ============
    $pdf->Ln(5);
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->SetFillColor($lightGray[0], $lightGray[1], $lightGray[2]);
    $pdf->SetTextColor($headerColor[0], $headerColor[1], $headerColor[2]);
    $pdf->Cell(0, 8, 'REGISTRATION INFORMATION', 1, 1, 'L', true);
    $pdf->SetFont('helvetica', '', 10);
    $pdf->SetTextColor(0, 0, 0);
    
    $regData = array(
        array('Consent Given:', ($patient['consent_given'] ?? 0) ? 'Yes' : 'No'),
        array('Consent Date:', !empty($patient['consent_date']) ? date('F j, Y H:i', strtotime($patient['consent_date'])) : 'N/A'),
        array('Created:', !empty($patient['created_at']) ? date('F j, Y H:i', strtotime($patient['created_at'])) : 'N/A'),
        array('Last Updated:', !empty($patient['updated_at']) ? date('F j, Y H:i', strtotime($patient['updated_at'])) : 'N/A'),
        array('User Account:', !empty($patient['user_id']) ? 'Registered (ID: ' . $patient['user_id'] . ')' : 'Regular Patient'),
        array('User Email:', htmlspecialchars($patient['user_email'] ?? 'N/A')),
        array('Unique Number:', htmlspecialchars($patient['unique_number'] ?? 'N/A')),
    );
    
    foreach ($regData as $row) {
        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->Cell(50, 7, $row[0], 0, 0, 'L');
        $pdf->SetFont('helvetica', '', 10);
        $pdf->Cell(0, 7, $row[1], 0, 1, 'L');
    }
    
    // Add separator between patients
    if ($index < count($patients) - 1) {
        $pdf->Ln(10);
        $pdf->SetDrawColor($borderColor[0], $borderColor[1], $borderColor[2]);
        $pdf->Line(15, $pdf->GetY(), 290, $pdf->GetY());
        $pdf->Ln(10);
    }
}

// Add summary page
$pdf->AddPage();
$pdf->SetFont('helvetica', 'B', 16);
$pdf->SetTextColor($secondaryColor[0], $secondaryColor[1], $secondaryColor[2]);
$pdf->Cell(0, 15, 'EXPORT SUMMARY', 0, 1, 'C');
$pdf->SetFont('helvetica', '', 12);
$pdf->SetTextColor(0, 0, 0);

$summaryData = array(
    array('Total Patients Exported:', count($patients)),
    array('Export Date:', date('F j, Y')),
    array('Export Time:', date('h:i A')),
    array('Generated by:', $_SESSION['user']['full_name']),
    array('User Role:', 'Staff'),
    array('Export Type:', 'Detailed Health Records'),
);

foreach ($summaryData as $row) {
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->Cell(70, 10, $row[0], 0, 0, 'L');
    $pdf->SetFont('helvetica', '', 12);
    $pdf->Cell(0, 10, $row[1], 0, 1, 'L');
}

// Add patient breakdown
$pdf->Ln(10);
$pdf->SetFont('helvetica', 'B', 12);
$pdf->Cell(0, 10, 'PATIENT BREAKDOWN:', 0, 1);
$pdf->SetFont('helvetica', '', 10);

$patientTypes = array();
foreach ($patients as $patient) {
    $type = $patient['patient_type'] ?? 'Regular Patient';
    if (!isset($patientTypes[$type])) {
        $patientTypes[$type] = 0;
    }
    $patientTypes[$type]++;
}

foreach ($patientTypes as $type => $count) {
    $pdf->Cell(0, 7, "• {$type}: {$count} patients", 0, 1, 'L');
}

// Add footer note
$pdf->Ln(15);
$pdf->SetFont('helvetica', 'I', 9);
$pdf->SetTextColor(100, 100, 100);
$pdf->MultiCell(0, 5, 'CONFIDENTIALITY NOTICE: This document contains confidential patient health information. Unauthorized disclosure, copying, or distribution is prohibited.', 0, 'C');
$pdf->MultiCell(0, 5, '© ' . date('Y') . ' Barangay Luz Health Center. All rights reserved.', 0, 'C');

// Output PDF
$pdf->Output('Barangay_Luz_Patient_Records_' . date('Y-m-d_His') . '.pdf', 'D');

// Clear session data
unset($_SESSION['pdf_export_data']);

// Helper function to calculate BMI
function calculateBMI($height, $weight) {
    if ($height > 0 && $weight > 0) {
        $heightInMeters = $height / 100;
        $bmi = $weight / ($heightInMeters * $heightInMeters);
        return number_format($bmi, 2);
    }
    return 'N/A';
}
?>